// frontend/src/app/events/[id]/not-found.tsx
import Link from 'next/link';
import { CalendarIcon, ArrowLeftIcon } from '@heroicons/react/24/outline';

export default function EventNotFound() {
  return (
 <div className="min-h-screen bg-white flex items-center justify-center py-12 px-4">
      <div className="bg-white rounded-xl shadow-lg p-8 max-w-md w-full text-center">
        <div className="w-16 h-16 bg-yellow-100 rounded-full flex items-center justify-center mx-auto mb-4">
          <CalendarIcon className="w-8 h-8 text-yellow-700" />
        </div>
        <h1 className="text-2xl font-bold text-neutral-900 mb-3">Event Not Found</h1>
        <p className="text-neutral-600 mb-6">
          This event may have been removed, unpublished, or the link is out of date.
        </p>
        <Link
          href="/events/"
          className="inline-flex items-center justify-center gap-2 w-full px-6 py-3 bg-black text-white font-semibold rounded-lg hover:bg-neutral-800 transition-colors"
        >
          <ArrowLeftIcon className="w-5 h-5" />
          Browse All Events
        </Link>
      </div>
    </div>
  );
}

// angular-frontend/src/app/pages/not-found.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';

@Component({
  selector: 'app-not-found',
  standalone: true,
  imports: [CommonModule, RouterModule],
  template: `
    <div class="min-h-screen flex items-center justify-center bg-gray-50">
      <div class="text-center">
        <h1 class="text-9xl font-bold text-gray-200">404</h1>
        <h2 class="text-4xl font-bold text-gray-900 mb-4">Page Not Found</h2>
        <p class="text-xl text-gray-600 mb-8 max-w-md mx-auto">
          The page you're looking for doesn't exist or has been moved.
        </p>
        <div class="space-x-4">
          <button 
            routerLink="/"
            class="bg-black text-white px-6 py-3 rounded-lg font-semibold hover:bg-gray-700 transition-colors duration-200"
          >
            Go Home
          </button>
          <button 
            (click)="goBack()"
            class="border border-gray-300 text-gray-700 px-6 py-3 rounded-lg font-semibold hover:bg-gray-50 transition-colors duration-200"
          >
            Go Back
          </button>
        </div>
      </div>
    </div>
  `
})
export class NotFoundComponent {
  goBack(): void {
    window.history.back();
  }
}
