// src/components/layout/Footer.tsx
'use client';

import React from 'react';
import Link from 'next/link';
import Image from 'next/image';
import { useRouter } from 'next/navigation';
import { BuildingLibraryIcon } from '@heroicons/react/24/outline';

interface FooterLink {
  name: string;
  href: string;
  type: 'route' | 'external';
}

interface FooterLinks {
  [key: string]: FooterLink[];
}

const Footer: React.FC = () => {
  const currentYear = new Date().getFullYear();
  const router = useRouter();

  const footerLinks: FooterLinks = {
    Services: [
      { name: 'All Services', href: '/services', type: 'route' },
      { name: 'Business Registration', href: '/business/registration', type: 'route' },
      { name: 'Tax Calculator', href: '/tools/tax-calculator', type: 'route' },
      { name: 'Document Checklist', href: '/tools/document-checklist', type: 'route' }
    ],
    Investment: [
      { name: 'Investment Opportunities', href: '/investments', type: 'route' },
      { name: 'Investment Onboarding', href: '/investment-onboarding', type: 'route' },
      { name: 'ROI Calculator', href: '/tools/roi-calculator', type: 'route' },
      { name: 'Agencies Directory', href: '/agencies', type: 'route' }
    ],
    Resources: [
      { name: 'Downloads', href: '/downloads', type: 'route' },
      { name: 'Tools & Calculators', href: '/tools', type: 'route' },
      { name: 'Invoice Generator', href: '/tools/invoice-generator', type: 'route' },
      { name: 'Support Center', href: '/support', type: 'route' }
    ],
    Contact: [
      { name: 'Phone: +256 775 692 335', href: 'tel:+256775692335', type: 'external' },
      { name: 'Email: support@onestopcentre.ug', href: 'mailto:support@onestopcentre.ug', type: 'external' },
      { name: 'About Us', href: '/about', type: 'route' }
    ]
  };

  const handleLinkClick = (link: FooterLink) => {
    if (link.type === 'route') {
      router.push(link.href as never);
    } else if (link.type === 'external') {
      if (link.href.startsWith('tel:') || link.href.startsWith('mailto:')) {
        window.location.href = link.href;
      } else {
        window.open(link.href, '_blank');
      }
    } else if (link.href.startsWith('#')) {
      const element = document.querySelector(link.href);
      if (element) {
        element.scrollIntoView({ behavior: 'smooth' });
      } else {
        // If element not found on current page, navigate to home and then scroll
        if (window.location.pathname !== '/') {
          router.push(`/${link.href}` as never);
        }
      }
    } else {
      window.open(link.href, '_blank');
    }
  };

  const openExternalLink = (url: string) => {
    window.open(url, '_blank');
  };

  return (
    <footer className="bg-gray-900 text-white">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-5 gap-8">
          <div className="lg:col-span-2">
            <div>
              <div className="flex items-center mb-4">
                <div className="w-12 h-12 bg-gradient-to-r from-primary-600 to-primary-800 rounded-lg overflow-hidden flex items-center justify-center mr-3 shadow-lg">
                  <Image 
                    src="/images/oneStopCenter-logo.jpeg" 
                    alt="OneStopCentre Uganda Official Logo" 
                    width={48}
                    height={48}
                    className="w-full h-full object-cover"
                  />
                  <span className="hidden text-white font-bold text-lg">OSC</span>
                </div>
                <div>
                  <h3 className="text-xl font-bold">OneStopCentre Uganda</h3>
                  <p className="text-sm text-gray-400 font-medium">InvestUganda simplified</p>
                </div>
              </div>
              <p className="text-gray-400 mb-4 max-w-md">
                Your gateway to streamlined government services, business registration, 
                and investment opportunities in Uganda.
              </p>
              <div className="flex space-x-4">
                <button 
                  onClick={() => openExternalLink('https://twitter.com/ugandainvest')}
                  className="text-gray-400 hover:text-white transition-colors"
                  title="Follow UIA on Twitter"
                  aria-label="Follow UIA on Twitter"
                >
                  <svg className="w-6 h-6" fill="currentColor" viewBox="0 0 24 24">
                    <path d="M24 4.557c-.883.392-1.832.656-2.828.775 1.017-.609 1.798-1.574 2.165-2.724-.951.564-2.005.974-3.127 1.195-.897-.957-2.178-1.555-3.594-1.555-3.179 0-5.515 2.966-4.797 6.045-4.091-.205-7.719-2.165-10.148-5.144-1.29 2.213-.669 5.108 1.523 6.574-.806-.026-1.566-.247-2.229-.616-.054 2.281 1.581 4.415 3.949 4.89-.693.188-1.452.232-2.224.084.626 1.956 2.444 3.379 4.6 3.419-2.07 1.623-4.678 2.348-7.29 2.04 2.179 1.397 4.768 2.212 7.548 2.212 9.142 0 14.307-7.721 13.995-14.646.962-.695 1.797-1.562 2.457-2.549z"/>
                  </svg>
                </button>
                <button 
                  onClick={() => openExternalLink('https://facebook.com/UgandaInvestmentAuthority')}
                  className="text-gray-400 hover:text-white transition-colors"
                  title="Follow UIA on Facebook"
                  aria-label="Follow UIA on Facebook"
                >
                  <svg className="w-6 h-6" fill="currentColor" viewBox="0 0 24 24">
                    <path d="M24 12.073c0-6.627-5.373-12-12-12s-12 5.373-12 12c0 5.99 4.388 10.954 10.125 11.854v-8.385H7.078v-3.47h3.047V9.43c0-3.007 1.792-4.669 4.533-4.669 1.312 0 2.686.235 2.686.235v2.953H15.83c-1.491 0-1.956.925-1.956 1.874v2.25h3.328l-.532 3.47h-2.796v8.385C19.612 23.027 24 18.062 24 12.073z"/>
                  </svg>
                </button>
                <button 
                  onClick={() => openExternalLink('https://linkedin.com/company/uganda-investment-authority')}
                  className="text-gray-400 hover:text-white transition-colors"
                  title="Connect with UIA on LinkedIn"
                  aria-label="Connect with UIA on LinkedIn"
                >
                  <svg className="w-6 h-6" fill="currentColor" viewBox="0 0 24 24">
                    <path d="M20.447 20.452h-3.554v-5.569c0-1.328-.027-3.037-1.852-3.037-1.853 0-2.136 1.445-2.136 2.939v5.667H9.351V9h3.414v1.561h.046c.477-.9 1.637-1.85 3.37-1.85 3.601 0 4.267 2.37 4.267 5.455v6.286zM5.337 7.433c-1.144 0-2.063-.926-2.063-2.065 0-1.138.92-2.063 2.063-2.063 1.14 0 2.064.925 2.064 2.063 0 1.139-.925 2.065-2.064 2.065zm1.782 13.019H3.555V9h3.564v11.452zM22.225 0H1.771C.792 0 0 .774 0 1.729v20.542C0 23.227.792 24 1.771 24h20.451C23.2 24 24 23.227 24 22.271V1.729C24 .774 23.2 0 22.222 0h.003z"/>
                  </svg>
                </button>
              </div>
            </div>
          </div>

          {Object.entries(footerLinks).map(([category, links]) => (
            <div key={category}>
              <div>
                <h4 className="text-lg font-semibold mb-4">{category}</h4>
                <ul className="space-y-2">
                  {links.map((link) => (
                    <li key={link.name}>
                      {link.type === 'route' ? (
                        <Link
                          href={link.href as never}
                          className="text-gray-400 hover:text-white transition-colors text-sm hover:text-primary-300"
                        >
                          {link.name}
                        </Link>
                      ) : (
                        <button
                          onClick={() => handleLinkClick(link)}
                          className="text-gray-400 hover:text-white transition-colors text-sm text-left hover:text-primary-300"
                        >
                          {link.name}
                        </button>
                      )}
                    </li>
                  ))}
                </ul>
              </div>
            </div>
          ))}
        </div>

        {/* Official Government Portals */}
        <div className="mt-12 pt-8 border-t border-gray-800">
          <div className="mb-8">
            <div className="flex items-center justify-center mb-4">
              <BuildingLibraryIcon className="w-6 h-6 text-primary-400 mr-2" />
              <h4 className="text-lg font-semibold text-primary-400">
                Official Government Portals
              </h4>
            </div>
            <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
              <div
                className="bg-gradient-to-r from-gray-800 to-gray-700 rounded-lg p-4 border border-gray-600 hover:border-primary-400 transition-all"
              >
                <div className="flex items-center space-x-3">
                  <div className="w-10 h-10 bg-blue-600 rounded-lg flex items-center justify-center">
                    <svg className="w-5 h-5 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 21V5a2 2 0 00-2-2H7a2 2 0 00-2 2v16m14 0h2m-2 0h-5m-9 0H3m2 0h5M9 7h1m-1 4h1m4-4h1m-1 4h1m-5 10v-5a1 1 0 011-1h2a1 1 0 011 1v5m-4 0h4" />
                    </svg>
                  </div>
                  <div className="flex-1">
                    <h5 className="font-semibold text-white">MyBusiness Portal</h5>
                    <p className="text-xs text-gray-400">Business registration & licensing</p>
                    <button
                      onClick={() => openExternalLink('https://mybusiness.go.ug/')}
                      className="text-primary-400 hover:text-primary-300 text-sm font-medium mt-1 transition-colors"
                    >
                      mybusiness.go.ug →
                    </button>
                  </div>
                </div>
              </div>

              <div
                className="bg-gradient-to-r from-gray-800 to-gray-700 rounded-lg p-4 border border-gray-600 hover:border-primary-400 transition-all"
              >
                <div className="flex items-center space-x-3">
                  <div className="w-10 h-10 bg-white rounded-lg flex items-center justify-center overflow-hidden p-1">
                    <Image 
                      src="/images/logos/UIA logo.png" 
                      alt="UIA Logo" 
                      width={60}
                      height={40}
                      className="w-full h-full object-contain"
                    />
                    <svg className="hidden w-5 h-5 text-green-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 8c-1.657 0-3 .895-3 2s1.343 2 3 2 3 .895 3 2-1.343 2-3 2m0-8c1.11 0 2.08.402 2.599 1M12 8V7m0 1v8m0 0v1m0-1c-1.11 0-2.08-.402-2.599-1M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
                    </svg>
                  </div>
                  <div className="flex-1">
                    <h5 className="font-semibold text-white">Uganda Investment Authority</h5>
                    <p className="text-xs text-gray-400">Investment opportunities & incentives</p>
                    <button
                      onClick={() => openExternalLink('https://ugandainvest.go.ug/')}
                      className="text-primary-400 hover:text-primary-300 text-sm font-medium mt-1 transition-colors"
                    >
                      ugandainvest.go.ug →
                    </button>
                  </div>
                </div>
              </div>

              <div
                className="bg-gradient-to-r from-gray-800 to-gray-700 rounded-lg p-4 border border-gray-600 hover:border-primary-400 transition-all"
              >
                <div className="flex items-center space-x-3">
                  <div className="w-10 h-10 bg-primary-600 rounded-lg flex items-center justify-center">
                    <svg className="w-5 h-5 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9.75 17L9 20l-1 1h8l-1-1-.75-3M3 13h18M5 17h14a2 2 0 002-2V5a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z" />
                    </svg>
                  </div>
                  <div className="flex-1">
                    <h5 className="font-semibold text-white">eBiz Portal</h5>
                    <p className="text-xs text-gray-400">Electronic business services</p>
                    <button
                      onClick={() => openExternalLink('https://ebiz.go.ug/')}
                      className="text-primary-400 hover:text-primary-300 text-sm font-medium mt-1 transition-colors"
                    >
                      ebiz.go.ug →
                    </button>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <div className="flex flex-col md:flex-row justify-between items-center">
            <p className="text-gray-400 text-sm">
              © {currentYear} OneStop Centre Uganda. All rights reserved.
            </p>
            <div className="flex space-x-6 mt-4 md:mt-0">
              <button 
                onClick={() => openExternalLink('https://www.ugandainvest.go.ug/privacy-policy')}
                className="text-gray-400 hover:text-white text-sm transition-colors"
              >
                Privacy Policy
              </button>
              <button 
                onClick={() => openExternalLink('https://www.ugandainvest.go.ug/terms-of-service')}
                className="text-gray-400 hover:text-white text-sm transition-colors"
              >
                Terms of Service
              </button>
              <button 
                onClick={() => openExternalLink('https://www.ugandainvest.go.ug/accessibility')}
                className="text-gray-400 hover:text-white text-sm transition-colors"
              >
                Accessibility
              </button>
            </div>
          </div>
        </div>
      </div>
    </footer>
  );
};

export default Footer;

// angular-frontend/src/app/components/footer.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';

@Component({
  selector: 'app-footer',
  standalone: true,
  imports: [CommonModule, RouterModule],
  template: `
    <footer class="bg-gray-900 text-white">
      <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
        <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
          
          <!-- Company Info -->
          <div class="space-y-4">
            <div class="flex items-center space-x-2">
              <img 
                src="/images/oneStopCenter-logo.jpeg" 
                alt="OneStop Centre Uganda"
                class="h-8 w-auto"
              >
              <span class="font-bold text-lg">OneStop Centre</span>
            </div>
            <p class="text-gray-300 text-sm">
              Simplifying business registration and investment processes in Uganda. 
              Your gateway to business success.
            </p>
            <div class="flex space-x-4">
              <a href="#" class="text-gray-400 hover:text-white transition-colors">
                <span class="sr-only">Facebook</span>
                <svg class="h-5 w-5" fill="currentColor" viewBox="0 0 20 20">
                  <path fill-rule="evenodd" d="M20 10C20 4.477 15.523 0 10 0S0 4.477 0 10c0 4.991 3.657 9.128 8.438 9.878v-6.987h-2.54V10h2.54V7.797c0-2.506 1.492-3.89 3.777-3.89 1.094 0 2.238.195 2.238.195v2.46h-1.26c-1.243 0-1.63.771-1.63 1.562V10h2.773l-.443 2.89h-2.33v6.988C16.343 19.128 20 14.991 20 10z" clip-rule="evenodd"></path>
                </svg>
              </a>
              <a href="#" class="text-gray-400 hover:text-white transition-colors">
                <span class="sr-only">Twitter</span>
                <svg class="h-5 w-5" fill="currentColor" viewBox="0 0 20 20">
                  <path d="M6.29 18.251c7.547 0 11.675-6.253 11.675-11.675 0-.178 0-.355-.012-.53A8.348 8.348 0 0020 3.92a8.19 8.19 0 01-2.357.646 4.118 4.118 0 001.804-2.27 8.224 8.224 0 01-2.605.996 4.107 4.107 0 00-6.993 3.743 11.65 11.65 0 01-8.457-4.287 4.106 4.106 0 001.27 5.477A4.073 4.073 0 01.8 7.713v.052a4.105 4.105 0 003.292 4.022 4.095 4.095 0 01-1.853.07 4.108 4.108 0 003.834 2.85A8.233 8.233 0 010 16.407a11.616 11.616 0 006.29 1.84"></path>
                </svg>
              </a>
              <a href="#" class="text-gray-400 hover:text-white transition-colors">
                <span class="sr-only">LinkedIn</span>
                <svg class="h-5 w-5" fill="currentColor" viewBox="0 0 20 20">
                  <path fill-rule="evenodd" d="M16.338 16.338H13.67V12.16c0-.995-.017-2.277-1.387-2.277-1.39 0-1.601 1.086-1.601 2.207v4.248H8.014v-8.59h2.559v1.174h.037c.356-.675 1.227-1.387 2.526-1.387 2.703 0 3.203 1.778 3.203 4.092v4.711zM5.005 6.575a1.548 1.548 0 11-.003-3.096 1.548 1.548 0 01.003 3.096zm-1.337 9.763H6.34v-8.59H3.667v8.59zM17.668 1H2.328C1.595 1 1 1.581 1 2.298v15.403C1 18.418 1.595 19 2.328 19h15.34c.734 0 1.332-.582 1.332-1.299V2.298C19 1.581 18.402 1 17.668 1z" clip-rule="evenodd"></path>
                </svg>
              </a>
            </div>
          </div>

          <!-- Quick Links -->
          <div class="space-y-4">
            <h3 class="text-lg font-semibold">Quick Links</h3>
            <ul class="space-y-2">
              <li><a routerLink="/about" class="text-gray-300 hover:text-white transition-colors">About Us</a></li>
              <li><a routerLink="/services" class="text-gray-300 hover:text-white transition-colors">Services</a></li>
              <li><a routerLink="/investments" class="text-gray-300 hover:text-white transition-colors">Investments</a></li>
              <li><a routerLink="/agencies" class="text-gray-300 hover:text-white transition-colors">Government Agencies</a></li>
              <li><a routerLink="/support" class="text-gray-300 hover:text-white transition-colors">Support</a></li>
            </ul>
          </div>

          <!-- Tools & Resources -->
          <div class="space-y-4">
            <h3 class="text-lg font-semibold">Tools & Resources</h3>
            <ul class="space-y-2">
              <li><a routerLink="/calculator" class="text-gray-300 hover:text-white transition-colors">Tax Calculator</a></li>
              <li><a routerLink="/roi-calculator" class="text-gray-300 hover:text-white transition-colors">ROI Calculator</a></li>
              <li><a routerLink="/document-checklist" class="text-gray-300 hover:text-white transition-colors">Document Checklist</a></li>
              <li><a routerLink="/registration-wizard" class="text-gray-300 hover:text-white transition-colors">Business Registration</a></li>
              <li><a routerLink="/downloads" class="text-gray-300 hover:text-white transition-colors">Downloads</a></li>
            </ul>
          </div>

          <!-- Contact Info -->
          <div class="space-y-4">
            <h3 class="text-lg font-semibold">Contact Us</h3>
            <div class="text-gray-300 space-y-2">
              <p class="flex items-center space-x-2">
                <svg class="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17.657 16.657L13.414 20.9a1.998 1.998 0 01-2.827 0l-4.244-4.243a8 8 0 1111.314 0z"></path>
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 11a3 3 0 11-6 0 3 3 0 016 0z"></path>
                </svg>
                <span>Kampala, Uganda</span>
              </p>
              <p class="flex items-center space-x-2">
                <svg class="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 5a2 2 0 012-2h3.28a1 1 0 01.948.684l1.498 4.493a1 1 0 01-.502 1.21l-2.257 1.13a11.042 11.042 0 005.516 5.516l1.13-2.257a1 1 0 011.21-.502l4.493 1.498a1 1 0 01.684.949V19a2 2 0 01-2 2h-1C9.716 21 3 14.284 3 6V5z"></path>
                </svg>
                <span>+256 (0) 123 456 789</span>
              </p>
              <p class="flex items-center space-x-2">
                <svg class="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 8l7.89 5.26a2 2 0 002.22 0L21 8M5 19h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z"></path>
                </svg>
                <span>support@onestopcentre.ug</span>
              </p>
            </div>
          </div>
        </div>

        <!-- Bottom Bar -->
        <div class="mt-8 pt-8 border-t border-gray-700 flex flex-col md:flex-row justify-between items-center">
          <p class="text-gray-400 text-sm">
            © {{ currentYear }} OneStop Centre Uganda. All rights reserved.
          </p>
          <div class="flex space-x-6 mt-4 md:mt-0">
            <a href="#" class="text-gray-400 hover:text-white text-sm transition-colors">Privacy Policy</a>
            <a href="#" class="text-gray-400 hover:text-white text-sm transition-colors">Terms of Service</a>
            <a href="#" class="text-gray-400 hover:text-white text-sm transition-colors">Cookie Policy</a>
          </div>
        </div>
      </div>
    </footer>
  `
})
export class FooterComponent {
  currentYear = new Date().getFullYear();
}
